---
title: "Relatórios reprodutíveis com R"
---

## Sobre o curso

Utilizaremos o Quarto (<https://quarto.org/>), e conheceremos como criar relatórios reprodutíveis com R ou Python, como: relatórios, apresentações em HTML, apresentações em powerpoint, relatórios em word, relatórios interativos, entre outros.

Aprenderemos também a criar relatórios reprodutíveis utilizando relatórios parametrizados, que permitem especificar parâmetros para customizar a análise, o que é muito útil para criar relatórios que podem ser reutilizados.

Além disso, o conceito de controle de versão com Git será apresentado. Também aprenderemos a disponibilizar o conteúdo criado no curso de forma online, através do GitHub.

## Temas abordados

-   O que é reprodutibilidade;

-   O que é o Quarto;

-   Como criar um documento reprodutível com Quarto usando R ou Python;

-   Como versionar os arquivos no Git e GitHub;

-   Como disponibilizar estes documentos HTML criados com Quarto na internet para que outras pessoas consigam acessar.
